# Generated by Django 5.2.7 on 2026-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
    ]
