# Generated by Django 5.2.7 on 2026-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_order', models.BooleanField(default=True)),
                ('new_customer', models.BooleanField(default=True)),
                ('low_stock', models.BooleanField(default=True)),
                ('payment_notification', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('dashboard_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
