# Generated by Django 5.2.7 on 2026-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_enabled', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='INR', max_length=10)),
                ('stripe_enabled', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
